### ISSUE TITLE
Consider making structure the first argument to get/set/etc... functions

### ISSUE THREAD

**Issue by tpoulsen** [tpoulsen/focus#10]
The original intention with making the lens the first argument was to support composing a long chain of lenses and piping into `Focus.view/2`, `Focus.set/3`, `Focus.over/3` etc….

There is obvious value in making the data structure the first argument, as focus could then slot directly into pipeline operations.

**Comment by mwgkgk** [comment]
Maybe support both? There's probably a clever naming scheme hiding somewhere in there, but I would appreciate this even if it's not :)

**Comment by tpoulsen** [comment]
Thanks for the comment @mwgkgk! This has been on the back-burner long enough; supporting both sounds ideal to me. Opted to allow the lens and data structure arguments to be passed in either order so that you can pass them in which ever way you prefer (or best makes sense for a given use case).
