### ISSUE TITLE
safe_view throwing an error when index doesn't exists

### ISSUE THREAD

**Issue by adleroliveira** [tpoulsen/focus#16]
la = Lens.make_lens("a")
lb = Lens.make_lens("b")
i0 = Lens.idx(0)

This works
la ~> i0 ~> lb |> Lens.safe_view(%{"a" => [%{"b" => 3}]})

This crashes
la ~> i0 ~> lb |> Lens.safe_view(%{"a" => []})

** (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:150: Keyword.get([], 0, nil)
             lib/focus.ex:147: anonymous fn/3 in Focus.compose/2

Shouldn't "safe_view" be safe and not crash when something is missing?

**Comment by smpoulsen** [comment]
Thanks for opening the issue. I should have some time later today to look
at it.
