### ISSUE TITLE
When to use lens/focus and when to use pattern matching?

### ISSUE THREAD

**Issue by collegeimprovements** [tpoulsen/focus#18]
Is there any convention or best practice for using lens vs pattern-matching?

**Comment by tpoulsen** [comment]
Thanks for the question! This is something I've been meaning to collect my thoughts on and write a blog post about. 

I don't necessarily think there's any convention really.

Personally, I generally think of pattern-matching in the context of function definitions and expression evaluation as ways to handle different cases of inputs and results respectively.

Lenses are more analogous to property accessors in languages with mutable records/classes/objects. They package up a way to get and set values inside of data structures in a composable, reusable way. Their utility really shines when updating or pulling values out of (deeply) nested data structures.

I've started drafting a blog post about this that will include some concrete examples. I'd like to get that out this week, but I hope this helps for now.

**Comment by moljac024** [comment]
Is that blog post out by any chance? If yes, can you post a link here? If not, can you post a link here once it is? 😄

**Comment by tpoulsen** [comment]
Sorry, not yet. I've got a few long flights this week and should have time to finish that draft. I'll definitely link here when it's up.

**Comment by tpoulsen** [comment]
The post is up here: https://travispoulsen.com/blog/posts/2017-09-07-lenses-and-pattern-matching.html. Hope it helps!
