### ISSUE TITLE
Lens.safe_view crashes after 3rd composed lens when there is index

### ISSUE THREAD

**Issue by adleroliveira** [tpoulsen/focus#19]
import Focus
data = %{a: []}
a = Lens.make_lens(:a)
b = Lens.make_lens(:b)
c = Lens.make_lens(:c)
d = Lens.make_lens(:d)
i0 = Lens.idx(0)

**This works fine:**
a ~> b ~> c ~> d |> Lens.safe_view(data)
{:error, {:lens, :bad_path}}

**This crashes**
a ~> i0 ~> b ~> c |> Lens.safe_view(data)
** (ArithmeticError) bad argument in arithmetic expression
    Lensable.Tuple.getter/2
    lib/lens/lens.ex:227: Lens.safe_view/2

**Comment by tpoulsen** [comment]
Thanks for the issue. Should have caught that in #16.

**Comment by adleroliveira** [comment]
Sorry bud. It didn't, this is why I'm creating this other issue.

take a look at line 24 of lensable.ex
if you run the example that I sent, the arguments are the following:
{{:error, {:lens, :bad_data_structure}}, :c}

The problem is the the function elem expects one tuple and one integer.
